version: "3"
services:
  nats-streaming:
    image: nats-streaming:0.11.2
    restart: unless-stopped
    ports:
      - "5222:4222"
    command: --user example_user --pass example_user_password --cid send-email-cluster
  sendemail-consumer:
    build: Consumer/.
    restart: unless-stopped
    depends_on:
      - nats-streaming
  sendemail-producer:
    build: Producer/.
    restart: unless-stopped
    ports:
      - "5080:8080"
    depends_on:
      - nats-streaming
