version: "3"
services:
  nats-streaming:
    image: nats-streaming:0.11.2
    restart: unless-stopped
    ports:
      - "5222:4222"
    command: --user example_user --pass example_user_password --cid send-email-cluster
  sendemail-consumer:
    build: Consumer/.
    restart: unless-stopped
    depends_on:
      - nats-streaming
      - mariadb
  sendemail-producer:
    build: Producer/.
    restart: unless-stopped
    ports:
      - "5080:8080"
    depends_on:
      - nats-streaming
      - mariadb
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: "example_db"
      MYSQL_USER: "example_user"
      MYSQL_PASSWORD: "example_password"
      MYSQL_ROOT_PASSWORD: "example_root_password"
    ports:
      - "4306:3306"
    volumes:
      - sendemail-db:/var/lib/mysql
volumes:
  sendemail-db: